---
environment: production
environmentCode: dev
container:
  messageQueueHost: DEVFFCINFSB1001.servicebus.windows.net
  paymentTopicAddress: ffc-pay-request-dev
  eventsTopicAddress: ffc-pay-events-dev
  azureStorageAccountName: devffcpayst1001
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false  
  azureStorageCreateContainers: false
  storageContainer: manual
  stagingFolder: staging
  inboundFolder: inbound
  archiveFolder: archive
  quarantineFolder: quarantine
secretProviderClass:
  azure:
    keyvaultName: DEVFFCINFKV1001
    objects:
      - objectName: devtest-ffcahwr-appInsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-injection
      type: Opaque
      data:
        - objectName: devtest-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
