---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  paymentTopicAddress: ffc-pay-request
  eventsTopicAddress: ffc-pay-events
  azureStorageAccountName: prdffcpayst1001
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false  
  azureStorageCreateContainers: false
  storageContainer: manual
  stagingFolder: staging
  inboundFolder: inbound
  archiveFolder: archive
  quarantineFolder: quarantine
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-injection
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
